name: Deploy to Vercel 
  
on: 
  push: 
    branches: 
      - main 
      - master 

# Esto silencia el warning de GitHub obligando a usar Node 24 internamente
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs: 
  deploy: 
    name: Deploy to Vercel (Production) 
    runs-on: ubuntu-latest 

    # IMPORTANTE: Esto obliga a los comandos a ejecutarse en tu carpeta de React
    defaults:
      run:
        working-directory: ./proyecto-react-sama
  
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
  
      - name: Setup Node.js 
        uses: actions/setup-node@v4 
        with: 
          node-version: 24 
          cache: 'npm' 
          # IMPORTANTE: Le dice a la caché dónde está exactamente el archivo
          cache-dependency-path: ./proyecto-react-sama/package-lock.json
  
      - name: Install dependencies 
        run: npm ci 
  
      - name: Build project 
        run: npm run build 
  
      - name: Install Vercel CLI 
        run: npm install --global vercel@latest 
  
      - name: Pull Vercel environment info 
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} 
  
      - name: Build for Vercel 
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} 
  
      - name: Deploy to Vercel 
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}